services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - internal

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    container_name: supertokens
    environment:
      POSTGRESQL_CONNECTION_URI: "${SUPERTOKENS_DATABASE_URL}"
      API_KEYS: "${SUPERTOKENS_API_KEY}"
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672//
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ALGORITHMS=${AUTH0_ALGORITHMS}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_RATE_LIMIT=${CELERY_RATE_LIMIT}
      - SUPERTOKENS_CONNECTION_URI=http://supertokens:3567
      - SUPERTOKENS_API_KEY=${SUPERTOKENS_API_KEY}
      - API_DOMAIN=${API_DOMAIN}
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
      - APP_NAME=${APP_NAME:-DailySpeakUp}
    depends_on:
      supertokens:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - internal

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_AUTH0_DOMAIN=${AUTH0_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
        - VITE_API_DOMAIN=${VITE_API_DOMAIN}
        - VITE_WEBSITE_DOMAIN=${VITE_WEBSITE_DOMAIN}
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - internal

  celery_worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -A src.services.email_impl.celery_app:app worker -l INFO --concurrency=1
    depends_on:
      - backend
      - rabbitmq
      - supertokens
    environment:
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672//
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ALGORITHMS=${AUTH0_ALGORITHMS}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_RATE_LIMIT=${CELERY_RATE_LIMIT}
      - SUPERTOKENS_CONNECTION_URI=http://supertokens:3567
      - SUPERTOKENS_API_KEY=${SUPERTOKENS_API_KEY}
      - API_DOMAIN=${API_DOMAIN}
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
      - APP_NAME=${APP_NAME:-DailySpeakUp}
    networks:
      - internal

networks:
  internal:
