services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - internal

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672//
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ALGORITHMS=${AUTH0_ALGORITHMS}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_RATE_LIMIT=${CELERY_RATE_LIMIT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - internal

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_AUTH0_DOMAIN=${AUTH0_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - internal

  celery_worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -A src.services.email_impl.celery_app:app worker -l INFO --concurrency=1
    depends_on:
      - backend
      - rabbitmq
    environment:
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672//
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ALGORITHMS=${AUTH0_ALGORITHMS}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_RATE_LIMIT=${CELERY_RATE_LIMIT}
    networks:
      - internal

networks:
  internal:
