#!/bin/bash

# Install script generated by Claude Sonnet 4.5 (Preview) through GitHub Copilot

set -e # Exit on error

echo "🔧 Installing project dependencies..."
echo ""

# Check Python version
echo "🔍 Checking Python version..."
if ! python3.13 --version &>/dev/null; then
    echo "❌ Python 3.13 is required but not found. Please run 'make setup' first."
    exit 1
fi

# Check Node.js version
echo "🔍 Checking Node.js version..."
if ! node --version | grep -q "v22\."; then
    echo "❌ Node.js 22 is required but not found. Please run 'make setup' first."
    exit 1
fi

# Create Python virtual environment
echo "🐍 Creating Python virtual environment..."
if [ ! -d ".venv" ]; then
    python3.13 -m venv .venv
    echo "✅ Virtual environment created at .venv"
else
    echo "✅ Virtual environment already exists"
fi

# Install backend dependencies
echo "📦 Installing backend dependencies..."
source .venv/bin/activate
pip install --upgrade pip
pip install -r backend/requirements.txt

# Install frontend dependencies
echo "📦 Installing frontend dependencies..."
cd frontend && npm install && cd ..

echo ""
echo "✅ Installation complete! Run 'make dev' to start development."
echo "💡 To activate the Python virtual environment manually, run: source .venv/bin/activate"
